### ISSUE TITLE
update github repo to what is on pypi

### ISSUE THREAD

**Issue by davidslac** [mpitid/pylabelme#3]
Hi, I came across a labelme package through pip, and it seems like this is the source repo for it, but what is on pypi looks alot newer than this, like the last todo in the readme is to refactor into a python package, which I guess is what is on pypi. Anyways, I'm looking for some starter code to add labeling to a machine learning pipeline, I've given up on standing up a MIT labelme webserver as I'm not a web programmer and can't debug it, I think I could do something with your code, but it would be nice work from the latest. No worries if not, I can always take what pip gives me.

**Comment by mpitid** [comment]
Hi, sorry for the late reply. I was not aware of the packaged project, it appears to be from a fork of pylabelme, you can find it's source here: https://github.com/wkentaro/labelme (or just look at the source tarball on pypi).
